name: Build PR image

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'src/entrypoint.sh'

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./Dockerfile"
          failure-threshold: warning

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/lablabs/bottlerocket-registry-auth-helper
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ github.event.pull_request.head.sha }}
            type=raw,value=pr${{ github.event.number }}-alpha

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
